### ISSUE TITLE
Code sample for a fully fluent turtle

### ISSUE THREAD

**Issue by dpellegr** [JustinSDK/dotSCAD#10]
Hi, please consider the code below.
It allows for constructing a polyline directly from a sequence of turtle commands. When constructing the list of 3D points, I automatically drop the turn commands which would produce duplicates.

It would also be interesting to add some commands to produce arcs in a straightforward way, but that is for another time.

```
use <turtle/t3d.scad>;
use <hull_polyline3d.scad>;

leng = 10;
angle = 120;
thickness = 1;

function drop_front(lst) =
  [ for (i=[1 : 1 : len(lst)-1]) lst[i] ];

function in(sub, s, i=0, j=0) = ( i==len(sub) ) 
  ? true
  : ( j==len(s) )
    ? false
    : in(sub, s, ( sub[i]==s[j] ) ? i+1 : 0, j+1);

function t3dc(pt, cmds, pts=[]) = (len(cmds) == 0) 
  ? concat(pts, [t3d(pt, "point")])
  : t3dc( t3d(pt, [cmds[0]]),
          drop_front(cmds), 
          concat( pts, in("turn", cmds[0][0]) ? [] : [t3d(pt, "point")] )
        );

pol = t3dc( t3d(point = [0, 0, 0]),
  [
    ["xforward", leng],
    ["zturn", angle],
    ["xforward", leng],
    ["zturn", angle],
    ["xforward", leng]
  ]
);   

hull_polyline3d(pol, thickness);
```

**Comment by JustinSDK** [comment]
Sound like what L-system does? 
https://github.com/JustinSDK/dotSCAD/blob/master/examples/turtle/lsystem2_collection.scad
https://github.com/JustinSDK/dotSCAD/blob/master/examples/turtle/lsystem3_collection.scad

**Comment by dpellegr** [comment]
Maybe, I am not sure. I just need to draw this pipe, nothing like those fancy fractals.

![pipe](https://i.imgur.com/NRGMGtG.png)

I just needed something to quickly avoid having to define every point explicitly as in the turtle examples.

**Comment by JustinSDK** [comment]
L-system functions will be published and documented in the next release. Your requirement seems like using a turtle to imitate freehand drawing. As you said, it might be useful in some situations. I'll consider implementing it some other day.

**Comment by dpellegr** [comment]
Exactly! The code above works properly, although having access to the
interior of the library it can probably be implemented in a more efficient
way. No need to rush. Thank you for the great library!

**Comment by dpellegr** [comment]
Ah, FYI, this is the code that I used to make the arc:

```
function arc(r, a, dir="z", $fn=$fn) =
  let(
    t=a/$fn, l=2*r*sin(t/2),
    lst = [for (i=[1:1:$fn]) [[str(dir,"turn"), (i==1)?t/2:t], ["xforward", l]] ] 
  )
  concat(lst, [lst[0][0]]);
```
It produces an ordered list of `$fn` `xforward` commands and `$fn+1` `turn` commands to create an arc of radius `r` and total bending angle `a` around the `dir` axis. Note how the first and last turn rotate by half of the angle step.

**Comment by JustinSDK** [comment]
2D `footprints2` function:

![footprints2](https://user-images.githubusercontent.com/3424741/81460834-58fb8c80-91da-11ea-9d04-ea4e7389f8b1.JPG)

```
use <turtle/turtle2d.scad>;
use <hull_polyline2d.scad>;

function _footprints2(cmds, t, leng, i = 0) =
    i == leng ? [] :
        let(
            nxt = turtle2d(cmds[i][0], t, cmds[i][1]),
            pts = _footprints2(cmds, nxt, leng, i + 1)
        )
        cmds[i][0] != "forward" ? pts : concat([turtle2d("pt", nxt)], pts);
    
// cmds: "turn", "forward"
function footprints2(cmds, start = [0, 0], angle = 0) = 
    let(
        t = turtle2d("create", start[0], start[1], angle),
        leng = len(cmds)
    )
    concat([turtle2d("pt", t)], _footprints2(cmds, t, leng));
 
function arc_cmds(radius, angle, steps) = 
    let(
        fa = angle / steps,
        ta = fa / 2,
        leng = sin(ta) * radius * 2
    )
    concat(
        [["turn", ta]],
        [
            for(i = [0:steps - 2])
            each [["forward", leng], ["turn", fa]]
        ],
        [["forward", leng], ["turn", ta]]
    );
    
poly = footprints2(
    concat(
        [
            ["forward", 10],
            ["turn", 90],
            ["forward", 10] 
        ], 
        arc_cmds(5, 180, 12),
        [
            ["turn", -90],
            ["forward", 10],
            ["turn", 90],
            ["forward", 10],
            ["turn", 90],
            ["forward", 10]
        ]
    )
);

hull_polyline2d(poly, width = 1);
```

**Comment by JustinSDK** [comment]
3D `footprints3` function:
![footprints3](https://user-images.githubusercontent.com/3424741/81467949-be697080-920e-11ea-8d03-2f69a971e86e.JPG)

```
use <hull_polyline3d.scad>;
use <turtle/footprints3.scad>;
 
function xy_arc_cmds(radius, angle, steps) = 
    let(
        fa = angle / steps,
        ta = fa / 2,
        leng = sin(ta) * radius * 2
    )
    concat(
        [["turn", ta]],
        [
            for(i = [0:steps - 2])
            each [["forward", leng], ["turn", fa]]
        ],
        [["forward", leng], ["turn", ta]]
    );

// cmds: "forward" ("xu_move"), "turn" ("zu_turn"), "roll" ("xu_turn"), "pitch" ("yu_turn")    
poly = footprints3(
    concat(
        [
            ["forward", 10],
            ["turn", 90],
            ["forward", 10] 
        ], 
        xy_arc_cmds(5, 180, 12),
        [
            ["pitch", -90],
            ["forward", 10],
            ["roll", -90]
        ],
        xy_arc_cmds(5, 180, 12),
        [
            ["forward", 10],
            ["roll", -90]
        ]
    )
);

hull_polyline3d(poly, thickness = 1);
```

**Comment by dpellegr** [comment]
Another improvement: you can avoid the extra brackets around commands when mixing them with arcs. For that I use the repack function. It fully flattens a nested list, then groups back the elements in sub-lists of the desired length (2 in this case). For instance:

```
let( L = [1,2,[3],[4,[5,6]]] )
fullflat( L ) => [1,2,3,4,5,6]
repack( L, 2) => [[1,2],[3,4],[5,6]]
repack( L, 3) => [[1,2,3],[4,5,6]]
```

so you can do:

```
poly = footprints3(
    repack([
        ["forward", 10],
        ["turn", 90],
        ["forward", 10] 
        xy_arc_cmds(5, 180, 12),
        ["pitch", 90],
        ["forward", 10],
        ["roll", 90]
        xy_arc_cmds(5, 180, 12),
        ["forward", 10]
    ])
);
```
You can also move the repack call inside the footprint3 function so that the user does not need to call it himself.

Here is an implementation of repack:
```
function flatten(l) = [ for (a = l) if (is_string(a)) a else for (b = a) b ];
function fullflat(l) = l == flatten(l) ? l : fullflat(flatten(l));
function repack(l, n=2) = let(lf=fullflat(l)) [ for (i=[0:n:len(lf)-1]) [for (j=[0:1:n-1]) lf[i+j] ]];
```

**Comment by JustinSDK** [comment]
`repack` is another story. I think it's better to be a utility function independent of footprints functions.

**Comment by dpellegr** [comment]
Yes of course. It just comes in very handy in here :)
