### ISSUE TITLE
Readme is incomprehensible to newbie

### ISSUE THREAD

**Issue by sandos** [JustinSDK/dotSCAD#13]
The top of the readme for this project does not explain what it is, what it does or what it enhances in openscad. Ok, fair enough, it does say: "Reduce the burden of mathematics when playing OpenSCAD."

The beginning of the first sentence goes on about library install locations for OpenSCAD. But why do I need this information?

Is this a new standard library for openscad, or a new core for openscad? I still do not know.

Adding a section "What this is" to the top of the readme with a sentence or two would help a lot.

**Comment by JustinSDK** [comment]
Are you an OpenSCAD newbie? If you're an OpenSCAD newbie, what you need is [the official documentation](http://www.openscad.org/documentation.html). You'll know the standard library is [here](http://www.openscad.org/cheatsheet/index.html).

What [The libraries tab](http://www.openscad.org/libraries.html) contains are all 3rd party libraries.

**Comment by JustinSDK** [comment]
I add some words on the top of README.

    Some of my 3D models require complex mathematics/algorithm. I extract them into dotSCAD. Hope it helps when you're playing OpenSCAD.

**Comment by sandos** [comment]
Thats good enough for me!
