### ISSUE TITLE
Defining shapes for path_extrude to use

### ISSUE THREAD

**Issue by cmodyssey** [JustinSDK/dotSCAD#14]
Hi,

Is it possible to change the shape_pts part way along, as the module moves it's way along the path_pts that it is given.

I want to start off as a 'U' shape and then change to half a 'U' shape.

Thanks for anyone who has any ideas.

Richard.

**Comment by JustinSDK** [comment]
You're having a similar requirement: [Is there a possibility to get a path out of a 2D object?](http://forum.openscad.org/Re-Is-there-a-possibility-to-get-a-path-out-of-a-2D-object-td30121.html).
