### ISSUE TITLE
convexity as optional parameter to sf_solidify

### ISSUE THREAD

**Issue by orjanekeberg** [JustinSDK/dotSCAD#19]
When previewing more complex shapes created via sf_solidify, it is often necessary to increase the complexity parameter passed to polyhedron (inside sf_solidify). It is currently necessary to modify the source code of sf_solidify itself to achieve this. It would be nice if you could make "convexity" an optional parameter to sf_solidify, sf_thicken, etc. which would simply be passed on to the internal polyhedron call.

**Comment by JustinSDK** [comment]
Done. Enjoy it :)
