### ISSUE TITLE
Error message in rounded_cube

### ISSUE THREAD

**Issue by andreaskielkopf** [JustinSDK/dotSCAD#20]
i got an Error-message when using rounded_cube with an array:

rounded_cube(size=[20,20,20],corner_r=.5,center=false);

There seem to be 2 unnecessary lines in rounded_cube.scad:

    half_l = half_x - edge_d;
    half_w = half_y - edge_d;
    half_h = half_z - edge_d;
    
**//    half_cube_leng = size / 2;  // produced the error
//    half_leng = half_cube_leng - edge_d;**
        
    pair = [1, -1];
    corners = [
        for(z = pair)

**Comment by JustinSDK** [comment]
Thanks, deleted.  :)
