### ISSUE TITLE
Archimedean spiral with non-approximated spacing

### ISSUE THREAD

**Issue by alexose** [JustinSDK/dotSCAD#21]
Hi there,

I'm currently working on a project that involves your excellent[ Archimedean spiral](https://openhome.cc/eGossip/OpenSCAD/ArchimedeanSpiral.html) code.  It's sort of a locking gear mechanism, and requires that things line up perfectly:

![image](https://user-images.githubusercontent.com/627264/132923538-9952f482-db09-49a1-bf4c-982373bac89e.png)

As you can see, the holes are spaced just a bit too close together, which I think is due to the approximation you mention in the document above.

I'll continue trying to work out the math on my own, but I haven't had much success so far.

Thanks!

**Comment by JustinSDK** [comment]
Arc length for Archimedean spiral is rather complex.
https://mathworld.wolfram.com/ArchimedesSpiral.html

Even though it's possible to space points accurately, the method might not be suitable or hard for implementation in OpenSCAD. 

The `archimedean_spiral` implementation of dotSCAD takes an approximation for satisfying most situations. Different approximations, however, are inaccurate in different ranges. You may check them in the following link to see what is more suitable for your case.
https://stackoverflow.com/questions/68735124/code-for-archimedean-spiral-with-equidistant-points-is-inaccurate-near-center

Hope it helps.

**Comment by alexose** [comment]
Fantastic.  I'll review those formulas and see if I can't get something more exact.
