### ISSUE TITLE
path_extrude.scad : scale parameter ignored for first sweep

### ISSUE THREAD

**Issue by jsteele22** [JustinSDK/dotSCAD#26]
Just discovered dotSCAD, and I'm loving it.  But on to a little issue I tripped upon....

Looking at the docs, I would expect the following code would produce a sweep of three rectangles that get progressively larger from top to bottom.  But the first 2 sections are identical.  In fact, if one of member of  points[]  is removed, the shape is a cube.

```
use <path_extrude.scad>;

w=8;
h=3;


rect = [
    [   -w/2,   -h/2,   0],
    [   +w/2,   -h/2,   0],
    [   +w/2,   +h/2,   0],
    [   -w/2,   +h/2,   0],
];

points = [
    [0,0, 10],
    [0,0, 5],
    [0,0,0]
];

path_extrude(   shape_pts = rect,
                path_pts = points,
                scale = 1.5);

```

**Comment by JustinSDK** [comment]
Thanks for reporting the issue. It's fixed. :)
