### ISSUE TITLE
shape_elipse is sometimes one point short because of floating point error

### ISSUE THREAD

**Issue by jmpreuss** [JustinSDK/dotSCAD#29]
For example if $fn=21 only 20 points are created.

I fixed with this hack, I'm sure there is a more graceful way.
Original code line 19
for(a = 0; a <= a_end; a = a + step_a) 
quick fix
for(a = 0; a <= a_end+0.0001; a = a + step_a) 
Thanks, Jason (@patterntoprint)

**Comment by JustinSDK** [comment]
fixed:

```openscad
        for(i = [0:frags - 1]) 
        let(a = i * step_a)
```
