### ISSUE TITLE
path_extrude() artifacts when path touches Z axis

### ISSUE THREAD

**Issue by lorf** [JustinSDK/dotSCAD#3]
When `path_extrude()` given a path that touches axis parallel to Z, it produces some artifacts in the touch area. Code to reproduce:
```
include <../src/rotate_p.scad>;
include <../src/bezier_curve.scad>;
include <../src/polysections.scad>;
include <../src/path_extrude.scad>;

shape_pts = [[5, -5], [5, 5], [-5, 5], [-5, -5]]; // 10mm square

// Path produced with bezier_curve():
//curve_pts = [[20,20,0],[10,10,10],[20,20,20]];
//path_pts = bezier_curve(0.1,curve_pts);
path_pts = [[20, 20, 0], [18.2, 18.2, 2], [16.8, 16.8, 4], [15.8, 15.8, 6], [15.2, 15.2, 8], [15, 15, 10], [15.2, 15.2, 12], [15.8, 15.8, 14], [16.8, 16.8, 16], [18.2, 18.2, 18], [20, 20, 20]];

path_extrude(shape_pts,path_pts,triangles="SOLID");
```
Result:
![image](https://user-images.githubusercontent.com/536698/39461102-c75b2e72-4d32-11e8-90e8-226236b2dd5a.png)

The workaround is to rotate the path so that it doesn't touch Z:
```
include <../src/rotate_p.scad>;
include <../src/bezier_curve.scad>;
include <../src/polysections.scad>;
include <../src/path_extrude.scad>;

shape_pts = [[5, -5], [5, 5], [-5, 5], [-5, -5]]; // 10mm square

// Path produced with bezier_curve():
//curve_pts = [[20,20,0],[10,10,10],[20,20,20]];
//path_pts = bezier_curve(0.1,curve_pts);
path_pts = [[20, 20, 0], [18.2, 18.2, 2], [16.8, 16.8, 4], [15.8, 15.8, 6], [15.2, 15.2, 8], [15, 15, 10], [15.2, 15.2, 12], [15.8, 15.8, 14], [16.8, 16.8, 16], [18.2, 18.2, 18], [20, 20, 20]];

path_pts_tmp = [ for(p=path_pts) rotate_p(rotate_p(p, [0,0,45]),[0,90,0]) ];
rotate([0,-90,-45])
    path_extrude(shape_pts,path_pts_tmp,triangles="SOLID");
```
![image](https://user-images.githubusercontent.com/536698/39461219-6cfe16c8-4d33-11e8-9404-a06ff2a7b798.png)

**Comment by JustinSDK** [comment]
The problem comes from the `section` function within `path_extrude` because it rotates each point of a section around Z first. When path touches Z axis and its projection on the XY plane makes a (nearly) 180-degree turn, the problem happens. 

Currently, avoiding such a path or the workaround you provided are ways to keep the problem away. 

I am trying to figure out a solution to solve it.

**Comment by TLC123** [comment]
You're looking for "frenet frame rotation" or similar solutions

**Comment by JustinSDK** [comment]
As far as I know, the problem of using only points to describe a path is that we don't have enough information about the path, such as how to rotate our cross-sections. 

The `path_extrude` module itself is actually a workaround for a path without a curve equation. The Frenet–Serret formulas seem not helpful here. 

If we have a curve equation such as Archimedean spiral, [cross_sections](https://openhome.cc/eGossip/OpenSCAD/lib-cross_sections.html) is more suitable. 

If we only have the points of a path and `path_extrude` cannot create the model we want, try [paths2section](https://openhome.cc/eGossip/OpenSCAD/lib-paths2sections.html) as an alternative. 

I'm studying the Frenet–Serret formulas. Maybe one day, I can come up with a `frenet–serret_extrude` module for the occasion we have the curve equation `r(t)`.

**Comment by PaulF8080** [comment]
I you split it into two extrusions, you can see the two faces/sections crossing each other. Not a bug in my opinion.
`path_ptsa = [[20, 20, 0], [18.2, 18.2, 2], [16.8, 16.8, 4], [15.8, 15.8, 6], [15.2, 15.2, 8], [15, 15, 10]];
path_extrude(shape_pts,path_ptsa,triangles="SOLID");

path_ptsb = [[15.2, 15.2, 12], [15.8, 15.8, 14], [16.8, 16.8, 16], [18.2, 18.2, 18], [20, 20, 20]];
path_extrude(shape_pts,path_ptsb,triangles="SOLID");
`
<img width="928" alt="test" src="https://user-images.githubusercontent.com/29189523/50797284-20b40900-1289-11e9-92f1-e575a7d4a59f.png">

**Comment by PaulF8080** [comment]
I was thinking that if it was a crossed section problem, a smaller shape would fix it. No.  Crossed isn't the problem. No overlap revealed a twist.  So I echoed the points sent to the polyhedron and pasted the points as pts in this code I added.
`module test_polysections_solid(points, faces) {
    echo(points); **pasted to pt= below**
    echo(faces);
}
colors = ["red", "green", "blue", "black"];
for (i = [0:len(pts)-1]){
    color(colors[i%len(colors)])
    translate(pts[i]) sphere(r=.5, center=true, $fn=60);
}`
<img width="928" alt="color" src="https://user-images.githubusercontent.com/29189523/50803086-09cbe180-129e-11e9-81b7-da7c5c954daf.png">

**Comment by JustinSDK** [comment]
`path_extrude` needs a way to know the time which the path projection on the XY plane makes a (nearly) 180-degree turn and does some modification on connecting points. I've tried some strategies but no perfect one.

**Comment by PaulF8080** [comment]
I'm having fun playing with your library and thought I would try debugging this. I got lost in the path_extrude code. I may try a pull request for feature I am trying to add. I haven't figured out the pull request process, though.

**Comment by JustinSDK** [comment]
I'm thinking that [Quaternion](https://en.wikipedia.org/wiki/Quaternion) might have chance to fix this issue.

**Comment by JustinSDK** [comment]
It seems that my recent idea works. Keep working on it.
![issue](https://user-images.githubusercontent.com/3424741/56864846-e1592600-69f9-11e9-9779-8b1d657fd938.JPG)

**Comment by JustinSDK** [comment]
Finally, I fix it...XDXDXD

![擷取](https://user-images.githubusercontent.com/3424741/56881685-ca671200-6a93-11e9-93ab-ff49c062b3ce.JPG)

**Comment by TLC123** [comment]
How did you solve it. Is it a a general solution for arbitrary paths and cross sections?

**Comment by lorf** [comment]
Awesome! Thank You!

**Comment by JustinSDK** [comment]
@TLC123 
Basic idea is shown below:
![issue3](https://user-images.githubusercontent.com/3424741/56887410-289bf100-6aa4-11e9-99bb-2f3d2d66a2e9.JPG)

In my opinion, there's no general solution for arbitrary paths because a path doesn't provide enough information about how to move sections. You may only try to find an acceptable solution without obvious bugs. 

(Yes, I hope that the current solution has no obvious bugs ^^  )

**Comment by JustinSDK** [comment]
@TLC123 
The basic idea is shown below:
![issue3](https://user-images.githubusercontent.com/3424741/56887837-30a86080-6aa5-11e9-8505-fa7fdace2de4.JPG)

In my opinion, there's no general solution for arbitrary paths because a path doesn't provide enough information about how to move sections. You may only try to find an acceptable solution without obvious bugs. 

(Yes, I hope the current solution has no obvious bugs ^^  )

**Comment by JustinSDK** [comment]
I add a `method` parameter to `path_extrude`. See [issue #5](https://github.com/JustinSDK/dotSCAD/issues/5) .
