### ISSUE TITLE
Slicer says "empty layers" with output from sf_thicken/sf_splines?

### ISSUE THREAD

**Issue by mconsidine** [JustinSDK/dotSCAD#32]
Hi,
I am trying to model an old telescope pier, using measurements that were taken at various vertical intervals on its surface.  It looks like this when rendered in openSCAD
![image](https://user-images.githubusercontent.com/586812/199045151-64be1440-5b38-4153-91bb-72652f406701.png)

This was modeled using dotSCAD because I needed the smooth curves and it renders without error.

When I pull it into a slicer (e.g. Prusa) though, I get an error saying there are empty layers in the area between the two "cube" calls in openSCAD, ie in the area created by the dotSCAD output.  In Meshmixer it renders fine and does not have any issues flagged, that I can see.  And using the "repair STL" option of Prusa doesn't fix anything.  So I can't figure out where something is going goofy.

I'm wondering if there is any trick I should be aware of in trying to mate surfaces created using sf_thicken/sf_splines?  Is there a better way to do this?  I thought that by using common edges that I would largely avoid holes/gaps/etc.  

I've attached a cleaned up version of the openSCAD file (with a .txt extension).  Apologies for it's length.

TIA,
mconsidine
[old_pier_demo.txt](https://github.com/JustinSDK/dotSCAD/files/9902572/old_pier_demo.txt)

**Comment by chehsunliu** [comment]
The author of this repository just passed away yesterday: https://www.ithome.com.tw/caterpillar?fbclid=IwAR0O9IAipAnfSZNXGH21IdDJNX-Rg3WDCwnnkGyml5wmf3a4hsE1JiilBI8&mibextid=Zxz2cZ.

**Comment by mconsidine** [comment]
My condolences. I'm sorry to hear of that.
Mconsidine 

EDIT:  This issue was caused by my having set the wall thickness to be too thin, relative to the printer/slicer settings.  There was nothing wrong with the code.

**Comment by hvegh** [comment]
My condolances, it saddens me to hear this.
hve
