### ISSUE TITLE
arc_path request

### ISSUE THREAD

**Issue by MrEdgeNL** [JustinSDK/dotSCAD#4]
Hello,
Thanks for sharing this awesome library.

I'm on a project and actually missing the arc_path, like there is a circle_path.
This seems somehow already implemented in the 2D-arc, generating a shape...
Is't possible for creating only an arc_path? 

Thanks.

**Comment by JustinSDK** [comment]
added.
https://openhome.cc/eGossip/OpenSCAD/lib-arc_path.html
