### ISSUE TITLE
"donut ring" using ellipse_extrude?

### ISSUE THREAD

**Issue by raycewest** [JustinSDK/dotSCAD#6]
Looking for a way to do a rotate_extrude in openscad but with different x and y distances, meaning the resulting ring would be elliptical rather than a circle.  ellipse_extrude seemed at first like what I'm looking for but seems to be something else when I actually try it out.  Any suggestions?  Thanks!

**Comment by JustinSDK** [comment]
Is this you want? 

```openscad
include <shape_ellipse.scad>;
include <shape_pentagram.scad>;
include <rotate_p.scad>;
include <polysections.scad>;
include <path_extrude.scad>;

path = shape_ellipse([40, 20], $fn = 48);
shape = shape_pentagram(5);

path_extrude(
    shape, 
    concat(path, [path[0]]), 
    closed = true, 
    method = "EULER_ANGLE"
);
```
![ellipse](https://user-images.githubusercontent.com/3424741/60393221-4ccb8b00-9b44-11e9-80b5-51d76100dccb.JPG)

**Comment by raycewest** [comment]
Bingo.  Thanks!
