### ISSUE TITLE
bijection_offset.scad problem

### ISSUE THREAD

**Issue by rvdb1** [JustinSDK/dotSCAD#7]
The order of the ofsetted points is incorrect.
You will not notice it with polygon of the ofsetted shape, but it appears if you use polyline2d.

Tested with version 1.3.3

Example:
include <polyline2d.scad>;
include <line2d.scad>;
include <bijection_offset.scad>;

shape = [
	[15, 0],
	[15, 30],
	[0, 20],
	[-15, 40],
	[-15, 0]
];

shape_o = bijection_offset(shape, 1);
color("green") polyline2d(points=shape,thickness=1,$fn=3);
color("red") polyline2d(points=shape_o,thickness=1,$fn=3);
echo(shape);
echo(shape_o);

**Comment by JustinSDK** [comment]
Fixed. 

BTW, it's `width`, not `thickness` for `polyline2d`.
