### ISSUE TITLE
Cannot do a difference between two path_extrude() objects

### ISSUE THREAD

**Issue by JanKalin** [JustinSDK/dotSCAD#8]
I'm trying to make custom-made knife angle guide (e.g. https://www.amazon.com/JSSHI-Knife-Sharpening-Sharpener-Kitchen/dp/B07DVYB367). I was planning to use a few solids created with path_extrude(), but I've hit a snag. When I try to subtract two of them, I get nothing.

This is the source:
[test.scad.txt](https://github.com/JustinSDK/dotSCAD/files/3991800/test.scad.txt) and this is what it looks like:
![image](https://user-images.githubusercontent.com/18305372/71313524-178c5f80-243a-11ea-83c1-73a294eb8bd9.png)

If I draw the two objects with `a(); #b();`, they are drawn as in the picture. If I comment the two lines, and call difference() nothing is shown. Perhaps I'm missing something basic, but I expected to be able to subtract the solids.

**Comment by JustinSDK** [comment]
I use OpenSCAD 2019.05 and nothing wrong. 
![a](https://user-images.githubusercontent.com/3424741/71315089-3e758080-2490-11ea-887a-3b9354feffff.JPG)

**Comment by JanKalin** [comment]
Sorry, didn't have time to check. It turns out that the problem is in OpenSCAD (or my understanding of its functioning). I also use 2019.05 and I see nothing on the preview. I need to press F10 - view surfaces, or render it, then it shows up.

**Comment by JustinSDK** [comment]
Try "Force Goldfeather"?

![b](https://user-images.githubusercontent.com/3424741/71405892-a46d2e00-2671-11ea-9e49-ac7bb33919bc.JPG)

**Comment by JanKalin** [comment]
Yes, that did the trick. Thank you!
